# Generated by Django 3.2.5 on 2021-07-18 00:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_money', models.PositiveIntegerField()),
                ('loan_period_in_days', models.PositiveIntegerField()),
                ('annual_percentage_rate', models.DecimalField(decimal_places=1, max_digits=3)),
                ('status', models.IntegerField(choices=[(0, 'FOUNDED'), (1, 'COMPLETED')], default='FOUNDED')),
                ('date_funded', models.DateField(null=True)),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.borrower')),
                ('investor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.investor')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(null=True)),
                ('amount_money', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_money', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)])),
                ('loan_period_in_days', models.PositiveIntegerField()),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(null=True)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('scheduled_payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scheduledpayment')),
            ],
        ),
        migrations.CreateModel(
            name='LoanOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_money', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)])),
                ('loan_period_in_days', models.PositiveIntegerField()),
                ('annual_percentage_rate', models.DecimalField(decimal_places=1, max_digits=3)),
                ('is_available', models.BooleanField(default=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.borrower')),
                ('investor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.investor')),
            ],
        ),
    ]
