# Generated by Django 3.2.5 on 2021-07-18 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanoffer',
            name='loan_request_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.loanrequest'),
            preserve_default=False,
        ),
    ]
