# Generated by Django 3.2.5 on 2021-07-18 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_loanoffer_loan_request_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='date_funded',
            new_name='date_founded',
        ),
    ]
