# Generated by Django 3.2.5 on 2021-07-18 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_date_funded_loan_date_founded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount_money',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='loanoffer',
            name='amount_money',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='amount_money',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)]),
        ),
    ]
